name: BUILD WAZUH CODE GENERATOR MULTIPLATFORM

on:
  push:
    branches:
      - main
    paths:
      - VERSION
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Set Version TAG
        run: echo "WAZUH_VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: wazuh-certs-generator/
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_IMAGE }}:${{ env.WAZUH_VERSION }}
            ${{ secrets.DOCKERHUB_IMAGE }}:latest
          platforms: |
            linux/amd64
            linux/arm64
